#!/bin/bash

 # Color directory
CD="$HOME/.Xresources"

# Fetch the Colors
#BG=$(cat ${CD} | grep -i background | tail -c 8)
BG="#1F222D"
FG=$(cat ${CD} | grep -i foreground | tail -c 8)

BLACK=$(cat ${CD} | grep -i color8 | tail -c 8)
RED=$(cat ${CD} | grep -i color9 | tail -c 8)
GREEN=$(cat ${CD} | grep -i color10 | tail -c 8)
YELLOW=$(cat ${CD} | grep -i color11 | tail -c 8)
BLUE=$(cat ${CD} | grep -i color12 | tail -c 8)
MAGENTA=$(cat ${CD} | grep -i color13 | tail -c 8)
CYAN=$(cat ${CD} | grep -i color14 | tail -c 8)
WHITE=$(cat ${CD} | grep -i color15 | tail -c 8)

# Fonts
#FONT1="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso8859-1"
#FONT2="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
FONT3="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
#FONT4="-benis-lemon-medium-r-normal--10-110-75-75-m-50-iso8859-1"
#FONT5="-nil-profont-medium-r-normal--10-110-72-72-c-60-iso8859-1"
#FONT6="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"

#FONT1="-Inconsolata-medium-r-normal--8-*-*-*-p-*-iso10646-1"
FONT1="Inconsolata:pixelsize=13"

# Panel 
PW=1870
PH=20
PX=20
PY=10



#Actions
VOLT="amixer sset Master toggle"
VOLU="amixer sset Master 2%+"
VOLD="amixer sset Master 2%-"
TMUS="mpc toggle"
NMUS="mpc next"
POW="~/.config/panel/bar_pop"

# Functions

#Workspace number 

 ws(){
#	ws=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
#	urgent=$(i3-msg -t get_workspaces | sed 's/.*"urgent":"\([^"]*\)".*/\1/'
  length=$(i3-msg -t get_workspaces | jq -r '. | length')
  for ((i=0; i<=$length; i++)); do
    workspace=$(i3-msg -t get_workspaces | jq -j '.['$i']')
    if [[ $(echo $workspace | jq -r '.urgent') = 'true' ]]; then
      urgent=$(echo $workspace | jq -r '.name')
    fi
    if [[ $(echo $workspace | jq -r '.focused') = 'true' ]]; then
      ws=$(echo $workspace | jq -r '.name')
    fi
  done
  echo "%{F$CYAN}${ws} %{F$RED}${urgent}"
}

music() {
  song=$(n=$(/home/loki/Documents/scripts/sp.sh current | grep 'Title' | cut -d' ' -f2- | awk '{$1=$1};1'); if [ -z "$n" ] ; then echo; else echo " $n"; fi)
  artist=$(n=$(/home/loki/Documents/scripts/sp.sh current | grep '^Artist' | cut -d' ' -f2- | awk '{$1=$1};1'); if [ -z "$n" ] ; then echo; else echo "$n"; fi)
  if [[ -n $song ]]; then
    music="$song"" - ""$artist"
  fi
  echo "%{F$WHITE}${music}"
}

 cpu(){
	cpu=$(mpstat -P ALL 1 1 | awk '(NR>11) {print $3+$5}' | paste -d " " - - - -)
	echo "%{F$MAGENTA} ${cpu}"
}
	
 net(){
	ipnet=$(ip=$(/sbin/ifconfig | grep eth0 -A 5 | sed '/inet addr:/!d;s/.*addr:\([0-9.]*\).*/\1/'); if [ ! -z "$ip" ]; then echo "$ip"; else echo "No Connection";fi)
	ip=$(ip -4 addr show wlp2s0 | grep -oP "(?<=inet ).*(?=/)")
  ping=$(pn=$(timeout .8 ping 185.40.64.65 -c 1 -s 24 | sed '2!d;s/.*time=\([0-9]*\).*/\1/'); if [ -z $pn ] ; then echo "No Connection"; else echo "${pn}ms"; fi)
	echo "%{F$CYAN} ${ip}   ${ping}"
}

ram(){
	ram=$(free -h | awk '/\Mem:/ {print $4}')
	echo "%{F$MAGENTA} ${ram}"
}

 temp(){
  temp=$(sensors | grep temp1 | head -n1 | sed 's/.*+\([0-9]*\).*/\1/')
	echo "%{F$MAGENTA} ${temp}C"
}

 clock(){
  clock=$(date "+%d %b %Y  %H:%M")
	echo "%{F$RED}${clock}"
}

 vol(){
  if [[ $(amixer get Master | grep off) ]]; then
    vol="Mute"
  else
	  vol=$(amixer get Master | grep % | awk '{print $5}' | sed 's/[^0-9\%]//g' | head -n1)
  fi
  echo "%{F$WHITE} ${vol}"
}

pow(){
	FOLD="/sys/class/power_supply"
	val=$(if [ -d $FOLD/BAT0 ]; then cat $FOLD/BAT0/capacity; fi)
	pow=$(if [ $(cat $FOLD/AC/online) = 1 ]; then if [ ! -d $FOLD/BAT0 ]; then echo ""; else echo "";fi; else if [[ $val < 12 ]]; then echo ""; else if [[ $val > 90 ]]; then echo ""; else echo "";fi; fi;fi)
	echo "%{F$MAGENTA}${pow} ${val}%"
}

while :; do 	
	 echo "   $(ws)  $(music)%{c}$(cpu)   $(temp)   $(ram)  $(pow)%{r}$(net)  %{A:$VOLT:}%{A4:$VOLU:}%{A5:$VOLD:}$(vol) %{A}%{A}%{A}  $(clock) %{A:$POW:}   %{A} "
	 sleep 0.1
done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -r 5 -R "#383C4A" -f "$FONT1" -f "$FONT3"  -B "$BG" -F "$FG" -p -d  | \
    while :; do read line; eval $line; done &
